title: Dependency injection container for PHP
description: PSR-11 compatible dependency injection container for PHP with automatic dependency bundling
plugins:
  - jekyll-polyglot
  - jekyll-remote-theme # add this line to the plugins list if you already have one
remote_theme: pages-themes/cayman@v0.2.0
languages: ["en", "ru"]
default_lang: "en"
exclude_from_localization: ["javascript", "images", "css", "public", "sitemap", "CNAME"]
parallel_localization: true
serial_default_lang: true
url: https://github.com/agdobrynin/di-container
show_downloads: false
github:
  owner_url: https://github.com/agdobrynin
  repository_name: kaspi/di-container
  is_project_page: true
  repository_url: https://github.com/agdobrynin/di-container
